title: "Boriana Savova"
description: "Artist portfolio of Boriana Savova"
url: "https://b-savova.github.io"

collections:
  artworks:
    output: true
    permalink: /works/:name/

defaults:
  - scope:
      path: ""
      type: "artworks"
    values:
      layout: "artwork"

exclude:
  - README.md
